# Generated by Django 4.2.10 on 2024-04-10 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('password', models.CharField(max_length=20)),
                ('currmonth', models.IntegerField(default=1)),
                ('currexpense', models.IntegerField(default=0)),
                ('budget', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.CharField(max_length=2000)),
                ('transtype', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.usermodel')),
            ],
        ),
    ]
