# Generated by Django 4.2.10 on 2024-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='debts',
            field=models.JSONField(default={}, verbose_name='Debts'),
        ),
    ]
